on:
    push:
        branches:
        - main
# Build java fx app for debian

jobs:
    build_deb:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up JDK 22
          uses: actions/setup-java@v2
          with:
              java-version: '22'
              distribution: 'corretto'
        - name: Extract Version from build.gradle
          id: get_version
          run: |
            VERSION=$(grep "^version" build.gradle | awk '{print $2}' | tr -d "'")
            echo "VERSION=$VERSION" >> $GITHUB_ENV
        - name: Build Debian Package
          run: ./gradlew jlink jpackage
        - name: Create Tag
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
            git push origin "v${{ env.VERSION }}"
